# Generated by Django 3.2.14 on 2022-07-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('writer', models.CharField(max_length=10, verbose_name='작성자')),
                ('title', models.CharField(max_length=50, verbose_name='제목')),
                ('content', models.CharField(max_length=255, verbose_name='내용')),
                ('hashtag', models.CharField(max_length=255, verbose_name='해시태그')),
                ('hits', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('likes', models.PositiveBigIntegerField(default=0, verbose_name='좋아요')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
            ],
        ),
    ]
