# Generated by Django 3.2.14 on 2022-07-21 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='delete_flag',
            field=models.BooleanField(default=False, verbose_name='삭제 상태'),
        ),
    ]
